name: Deployment

on:
  workflow_call:  # This workflow can only be called by other workflows

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Connect to server and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          username: ${{ secrets.PROD_SSH_USERNAME }}
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ inputs.docker_image }}:prod
            docker stack rm prod-server
            docker stack deploy -c ~/gymsBroBackend/docker-compose.yaml prod-server

  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - name: Connect to dev server and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USERNAME }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ inputs.docker_image }}:dev
            docker stack rm dev-server
            docker stack deploy -c ~/gymsBroBackend/docker-compose.yaml dev-server