name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  push:
    needs: build
    if: github.event_name == 'push'
    uses: ./.github/workflows/push.yml

  deployment:
    needs: push
    if: github.event_name == 'push'
    uses: ./.github/workflows/deployment.yml