name: Push Docker Image

on:
  workflow_call:  # This workflow can only be called by other workflows

env:
  DOCKER_IMAGE: npwskp/gymsbro

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment suffix
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/develop' ]]; then
            echo "ENV_SUFFIX=dev" >> $GITHUB_ENV
          else
            echo "ENV_SUFFIX=prod" >> $GITHUB_ENV
          fi

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: /tmp

      - name: Load Docker image
        run: docker load --input /tmp/image.tar

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag ${{ env.DOCKER_IMAGE }}:${{ env.ENV_SUFFIX }} ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          docker push ${{ env.DOCKER_IMAGE }}:${{ env.ENV_SUFFIX }}
          docker push ${{ env.DOCKER_IMAGE }}:${{ github.sha }} 